### ISSUE TITLE
建议在首行加上#coding=utf-8，否则部分英文linux不支持编译（例如树莓派）

### ISSUE THREAD

**Issue by h1997l1997** [rvfu/fuckNuaa#3]

**Comment by rvfu** [comment]
编码声明已经添加，但您的部分linux设备不能正常运行程序的原因并非如此。
python2的[默认编码方式](https://docs.python.org/2/howto/unicode.html)是ascii，python3的[默认编码方式](https://docs.python.org/3/tutorial/interpreter.html#source-code-encoding)是utf-8）。
本项目中的程序所有语法都遵循python3的语法，python3与python2并不兼容。
而且，许多代码的运行要求是处于南航大校园网环境。

**Comment by h1997l1997** [comment]
fjj的死党是也，树莓派默认python2，改用py3之后可以运行
